version: '3.8'

services:
  mc_batch:
    container_name: multi_cloud_batch
    image: multi-cloud-batch:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - "./mc-batch-logs:/app/logs"
    networks:
      - bridge_network
    #    network_mode: host
    #    hostname: mc-batch
    environment:
      - PROFILES=${PROFILES}
      - SERVER_PORT=${SERVER_PORT}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_SECRET_KEY=${AWS_SECRET_KEY}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
      - AWS_REGION=${AWS_REGION}
      - AWS_PROFILE=${AWS_PROFILE}
      - AWS_SECRET_PREFIX=${AWS_SECRET_PREFIX}
    ports:
      - "8050:8080"

networks:
  bridge_network:
    driver: bridge
