server:
  port: 8088

spring:
  datasource:
    hikari:
      maximum-pool-size: 30
  application:
    name: 'Multi Cloud Batch'
    version: @project.version@
  profiles:
    active: ${PROFILES:dev}
  thymeleaf:
    cache: false
